// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC12KHdETJEW8yBaa6UdkXV_m2IYAoJLho',
    appId: '1:518523111352:web:42a05ddbbce0f5b877714d',
    messagingSenderId: '518523111352',
    projectId: 'authentication-1a147',
    authDomain: 'authentication-1a147.firebaseapp.com',
    storageBucket: 'authentication-1a147.firebasestorage.app',
    measurementId: 'G-XZZE7QG70G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8U1lVYc-sb5yTCuxKy1WC_isS7fbLR68',
    appId: '1:518523111352:android:f4684d06295ec8e177714d',
    messagingSenderId: '518523111352',
    projectId: 'authentication-1a147',
    storageBucket: 'authentication-1a147.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASDq-FO2f_KOU88fx4GqA5r0L6_HNLtGY',
    appId: '1:518523111352:ios:44ec13cb4a107d6f77714d',
    messagingSenderId: '518523111352',
    projectId: 'authentication-1a147',
    storageBucket: 'authentication-1a147.firebasestorage.app',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASDq-FO2f_KOU88fx4GqA5r0L6_HNLtGY',
    appId: '1:518523111352:ios:44ec13cb4a107d6f77714d',
    messagingSenderId: '518523111352',
    projectId: 'authentication-1a147',
    storageBucket: 'authentication-1a147.firebasestorage.app',
    iosBundleId: 'com.example.authentication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC12KHdETJEW8yBaa6UdkXV_m2IYAoJLho',
    appId: '1:518523111352:web:b82de819c04bef0077714d',
    messagingSenderId: '518523111352',
    projectId: 'authentication-1a147',
    authDomain: 'authentication-1a147.firebaseapp.com',
    storageBucket: 'authentication-1a147.firebasestorage.app',
    measurementId: 'G-NX4LND1DED',
  );
}
